VERSION="1.0.0"

[[PRINCIPALS]]
name="FIXORA"
email="fixoratk@gmail.com"

[[CURRENCIES]]
code="FXR"
issuer="GAKBW77NDG6GH2AAD7QVOSXRRSODQ3R62IKWUGFVIJTFIAZBRUMUK7RW"
display_decimals=2
name="Fixora Token"
desc="The native utility token for Fixora Marketplace, used for rewarding professional service providers and unlocking premium platform features within the Pi Network ecosystem."
image="https://aybapp.github.io/FXR/FXR.png"
